/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsultingRouteImport } from './routes/consulting'

const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/consulting': typeof ConsultingRoute
}
export interface FileRoutesByTo {
  '/consulting': typeof ConsultingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/consulting': typeof ConsultingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/consulting'
  fileRoutesByTo: FileRoutesByTo
  to: '/consulting'
  id: '__root__' | '/consulting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsultingRoute: typeof ConsultingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ConsultingRoute: ConsultingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
